name       : weechat
version    : 2.0.1
release    : 23
source     :
    - https://weechat.org/files/src/weechat-2.0.1.tar.bz2 : 425f3268fc9cb2a70610554380f1d5711bb8471178ef97159ec85918bea77b4b
license    : GPL-3.0
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(lua-5.3)
    - pkgconfig(python-2.7)
    - pkgconfig(ruby-2.3)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python2 \
        -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so
build      : |
    %make
install    : |
    %make_install
