name       : weechat
version    : '3.3'
release    : 52
source     :
    - https://github.com/weechat/weechat/archive/refs/tags/v3.3.tar.gz : a9834f84d8b6b37bcea107fe5a283699f1312da6df9dd70d675e70df65cee7c9
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - pkgconfig(ruby-2.7)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON -DENABLE_JAVASCRIPT=OFF -DENABLE_PHP=OFF -DWITH-DEBUG=1
build      : |
    %make
install    : |
    %make_install
