name       : weechat
version    : '2.6'
release    : 36
source     :
    - https://github.com/weechat/weechat/archive/v2.6.tar.gz : fa416e43f86a67e521bc1a4c1949d2032495864568af31016b9840bcfca35033
license    : GPL-3.0
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - pkgconfig(ruby-2.6)
    - pkgconfig(tcl)
    - libgcrypt-devel
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON
build      : |
    %make
install    : |
    %make_install
