name       : weechat
version    : 1.4
release    : 6
source     :
    - https://weechat.org/files/src/weechat-1.4.tar.bz2 : e06d9949ccececdd9692c95c41304c2f7fe9ec47b5eedd0d0a8529f6a3c1ddd4
license    : GPL-3.0
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(lua-5.1)
    - pkgconfig(python-2.7)
    - pkgconfig(ruby-2.2)
    - pkgconfig(tcl)
    - perl
rundeps   :
    - perl
setup      : |
    ./autogen.sh
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
