name       : weechat
version    : '3.0'
release    : 44
source     :
    - https://github.com/weechat/weechat/archive/v3.0.tar.gz : bd23fe4c775fea5e140ad6aed696daa22dee97a298a37211d0da2b45935bf076
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - pkgconfig(ruby-2.7)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON -DENABLE_JAVASCRIPT=OFF -DENABLE_PHP=OFF -DWITH-DEBUG=1
build      : |
    %make
install    : |
    %make_install
