name       : weechat
version    : 4.0.2
release    : 68
source     :
    - https://github.com/weechat/weechat/archive/refs/tags/v4.0.2.tar.gz : eb3bf65f9c2411d85d4841187182d7ea378ff64b82c2eaf0cef885f818ec8753
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant-2)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(libzstd)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - pkgconfig(ruby-3.2)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON -DENABLE_JAVASCRIPT=OFF -DENABLE_PHP=OFF -DWITH-DEBUG=1
build      : |
    %make
install    : |
    %make_install
