name       : weechat
version    : '1.9'
release    : 18
source     :
    - https://weechat.org/files/src/weechat-1.9.tar.bz2 : 8c924a71a35becb169b9e0a6b4628997503f30a74563c0e2d0bdf55dbb82d675
license    : GPL-3.0
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(lua-5.1)
    - pkgconfig(python-2.7)
    - pkgconfig(ruby-2.2)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python2 \
        -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so
build      : |
    %make
install    : |
    %make_install
