name       : weechat
version    : '3.4'
release    : 54
source     :
    - https://github.com/weechat/weechat/archive/refs/tags/v3.4.tar.gz : 4b6cacf82d02eb1b327cc293bac8136f5d4220fe0de00383fac5558c0fde6197
license    : GPL-3.0-or-later
summary    : WeeChat is a fast, light and extensible chat client.
component  : network.irc
description: |
    WeeChat is a fast, light and extensible chat client.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(enchant)
    - pkgconfig(gnutls)
    - pkgconfig(guile-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgcrypt)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - pkgconfig(ruby-3.0)
    - pkgconfig(tcl)
    - perl
rundeps    :
    - perl
setup      : |
    %cmake -DENABLE_ENCHANT=ON -DENABLE_JAVASCRIPT=OFF -DENABLE_PHP=OFF -DWITH-DEBUG=1
build      : |
    %make
install    : |
    %make_install
